[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "whisp"
version = "0.3.0-dev"
description = "Voice-typing helper powered by whisper.cpp"
authors = [{ name = "Jakov", email = "jakov.iv@proton.me" }]
requires-python = ">=3.9"
dependencies = [
  "sounddevice>=0.5",
  "pyqt6>=6.9",
  "platformdirs>=4.2",
  "pyyaml>=6.0",
  "pyperclip>=1.9",
  "psutil>=5.9",
  "numpy>=1.26",
]

[project.scripts]
whisp = "whisp.__main__:main"
