# pyproject.toml  — new, complete file
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "whisp"
version = "0.2.0"
description = "Speech-to-text dictation tool that self-builds whisper.cpp on first run"
authors = [{ name = "Jakov", email = "jakov.iv@proton.me" }]
requires-python = ">=3.9"
dependencies = [
  "sounddevice",
  "pyqt6",
  "platformdirs",
  "pyyaml",
  "requests",
  "pyperclip",
  "psutil",
  "numpy",
  "keyboard",
  "gitpython>=3.1",
]

[project.scripts]
whisp = "whisp.__main__:main"
