aipp_enabled: false
aipp_model: llama2
aipp_prompt_alt: ''
aipp_prompt_default: Summarize the following text
aipp_provider: local
app_mode: whisp
clipboard_backend: auto
collect_metrics: false
hotkey_record: ctrl+alt+r
log_enabled: true
log_file: ''
performance_log_file: performance_data.csv
simulate_typing: true
typing_delay: 10
verbosity: false
whisper_binary: whisper.cpp/build/bin/whisper-cli
model_path: whisper.cpp/models/ggml-base.en.bin