app_mode: whisp
clipboard_backend: auto
hotkey_record: ctrl+alt+r
log_enabled: true
log_location: ''
collect_metrics: false
collect_accuracy_rating: true
performance_log_file: performance_data.csv
simulate_typing: true
typing_delay: 1
typing_start_delay: 0.15
verbosity: true
whisper_binary: whisper.cpp/build/bin/whisper-cli
model_path: whisper.cpp/models/ggml-base.en.bin

# --- ✨ AIPP (AI post-processing) ------------------------------------------
aipp_enabled: false
aipp_provider: ollama
aipp_active_prompt: default

# New: List of models per provider
aipp_models:
  ollama: ["llama3.2:latest", "mistral:latest", "gemma3:latest", "qwen2.5-coder:1.5b"]
  openai: ["gpt-4o-mini-2024-07-18"]
  anthropic: ["claude-3-opus-20240229", "claude-3-haiku"]
  xai: ["grok-3-latest"]

# New: Selected model per provider
aipp_selected_models:
  ollama: "llama3.2:latest"
  openai: "gpt-4o-mini-2024-07-18"
  anthropic: "claude-3-opus-20240229"
  xai: "grok-3-latest"

aipp_prompts:
  default: "Rewrite the following input so that it is clean and concise. Do not add any additional text or commentary. Just the rewritten text."
  prompt1: ""
  prompt2: ""
  prompt3: ""