name: Release AppImage

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g. v1.3.2)"
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set version env
        run: echo "APP_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Install appimage-builder (snap)
        run: |
          sudo snap install appimage-builder --classic
          echo "/snap/bin" >> $GITHUB_PATH

      - name: Build AppImage
        run: |
          appimage-builder --recipe AppImageBuilder.yml --skip-tests

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: VOXD-${{ env.APP_VERSION }}-x86_64.AppImage
          path: ./*.AppImage
