name: Release AppImage

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g. v1.3.2)"
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set version env
        run: echo "APP_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Install host deps for AppImage build
        run: |
          sudo apt update
          sudo apt install -y libfuse2 squashfs-tools desktop-file-utils zsync curl file

      - name: Download appimage-builder (AppImage)
        run: |
          set -e
          URL=$(curl -s https://api.github.com/repos/AppImageCrafters/appimage-builder/releases/latest \
            | grep -Eo 'https://[^"]+x86_64\.AppImage' | head -n1)
          echo "Using: $URL"
          curl -L "$URL" -o appimage-builder.AppImage
          chmod +x appimage-builder.AppImage

      - name: Build AppImage
        run: |
          ./appimage-builder.AppImage --recipe AppImageBuilder.yml --skip-tests | cat

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: VOXD-${{ env.APP_VERSION }}-x86_64.AppImage
          path: ./*.AppImage
